name: Publish
on:
  push:
    branches:
      - master
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js (NPMJS) ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Deploy
      run: npm run deploy
      env:
        SANITY_AUTH_TOKEN: ${{secrets.SANITY_AUTH_TOKEN}}
